project:
  type: website
  output-dir: docs

website:
  title: "Jessica Kraft, Ph.D."
  navbar:
    search: true
    right:
      - icon: "bi bi-file-earmark-person"
        text: "CV"
        href: cv.pdf
        target: _blank
      - icon: github
        text: GitHub
        href: https://github.com/jessicankraft
        target: _blank
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/jessicankraft/
        target: _blank
      - text: ResearchGate
        href: https://www.researchgate.net/profile/jessicankraft
        target: _blank
        
format:
  html:
    theme: cosmo
    css: styles.css

editor: source



